### ISSUE TITLE
Remote operation

### ISSUE THREAD

**Issue by R1BLH** [ExpertSDR3/ExpertSDR3-MANUAL#1]
Страница 124.

`3. Login into your Profile using the following this link`

Указан url тот же, что и для регистрации -- https://cloud.eesdr.com:5450/reg.html

Правильный url: https://cloud.eesdr.com:5450/auth.html

**Comment by rvolchkov** [comment]
Спасибо, исправлено.

**Comment by rvolchkov** [comment]
Fixed
